apiVersion: "openstack.stable.sap.cc/v1"
kind: "OpenstackSeed"
metadata:
  name: ironic-seed
spec:
  requires:
    - monsoon3/domain-default-seed
    - monsoon3/domain-ccadmin-seed

  roles:
    - cloud_baremetal_admin
    - baremetal_admin
    - baremetal_viewer
    - cloud_compute_admin
    - cloud_network_admin

  services:
  - name: ironic
    type: baremetal
    description: Openstack baremetal provisioning service
 # uncomment once moved to helm-charts
 #    endpoints:
 #    - interface: admin
 #      region: {{ .Values.global.region }}
 #      url: https://{{ include "ironic_api_endpoint_host_public" .}}
 #    - interface: internal
 #      region: {{ .Values.global.region }}
 #      url: http://ironic-api.{{ .Release.Namespace }}.svc.kubernetes.{{ .Values.global.region }}.{{ .Values.global.tld }}:6385
 #    - interface: public
 #      region: {{ .Values.global.region }}
 #      url: http://ironic-api.{{ .Release.Namespace }}.svc.kubernetes.{{ .Values.global.region }}.{{ .Values.global.tld }}:6385

  flavors:
    - name: "zh1mlx1.large"
      id: "1000"
      vcpus: "120"
      ram: "1048576"
      disk: "837"
      is_public: false
      description: HANA Baremetal 2 socket
      extra_specs:
        "capabilities:cpu_arch": "x86_64"
    - name: "zh2mlx1.xlarge"
      id: "1010"
      vcpus: "88"
      ram: "2097152"
      disk: "400"
      is_public: false
      description: HANA Baremetal 4 socket
      extra_specs:
        "capabilities:cpu_arch": "x86_64"
    - name: "zh2mlx1.2xlarge"
      id: "1020"
      vcpus: "172"
      ram: "4194304"
      disk: "400"
      is_public: false
      description: HANA Baremetal 8 socket
      extra_specs:
        "capabilities:cpu_arch": "x86_64"
    - name: "zh2mlx1.3xlarge"
      id: "1030"
      vcpus: "172"
      ram: "6291456"
      disk: "400"
      is_public: false
      description: HANA Baremetal 8 socket
      extra_specs:
        "capabilities:cpu_arch": "x86_64"

  domains:
  - name: Default
    users:
    - name: ironic
      description: Ironic Service
      #password: {{ .Values.global.ironic_service_password }}
      roles:
      - project: service
        role: service
      - project: service
        role: cloud_network_admin
      - project: service
        role: cloud_compute_admin
      - project: service
        role: cloud_baremetal_admin
  - name: ccadmin
    projects:
    - name: master
      roles:
      - user: image-build@Default
        role: cloud_baremetal_admin
    groups:
    - name: CCADMIN_CLOUD_ADMINS
      roles:
      - project: master
        role: cloud_baremetal_admin
      - project: cloud_admin
        role: cloud_baremetal_admin

  - name: ccadmin
    projects:
    - name: master
      flavors:
      - "1000"
      - "1010"
      - "1020"
      - "1030"
